apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-ticker
spec:
  template:
    spec:
      containers:
        - name: stock-ticker
          image: docker.io/tokiwong/stock-ticker:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: stock-ticker-env
            - configMapRef:
                name: stock-ticker-env
          ports:
          - name: application
            containerPort: 8080
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
