apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

commonLabels:
  app: stonks

resources:
- deployment.yaml
- service.yaml
- secret.yaml

configMapGenerator:
- name: stock-ticker-env
  literals:
    - N_DAYS="7"
    - STOCK_SYMBOL="FORG"
