apiVersion: v1
kind: Service
metadata:
  name: stock-ticker
  labels:
    app: stock-ticker
spec:
  type: ClusterIP
  ports:
  - name: application
    port: 8080
    targetPort: 8080
  selector:
    app: stock-ticker
